### ISSUE TITLE
Measurement of isolated solid rectangles produces unexpected results

### ISSUE THREAD

**Issue by ianwilliamson** [NanoComp/imageruler#4]
I noticed that the existing notebook examples and test cases do not consider isolated solid rectangular features, so I tried the ruler on the set of patterns shown below:

![image](https://user-images.githubusercontent.com/8869582/228031375-853c355f-39f2-43dd-9f65-f64aadaa7447.png)

```python
import imageruler
import numpy as np


def generate_square(width, height, padding):
  return np.pad(np.ones((width, height), dtype=float), padding)


widths = [5, 10, 15, 20, 25, 50]
height = 50
padding = 50

squares = [generate_square(width, height, padding) for width in widths]

mfs = [
    imageruler.ruler.minimum_length_solid(square, pad_mode='edge')
    for square in squares
]
```

After running the code above, `mfs` has the value:

```
[5.671875, 9.302734375, 10.57421875, 10.529296875, 9.4765625, 11.6220703125]
```

which does not correlate with the values in `widths`.

**Comment by stevengj** [comment]
This is correct — a sharp corner corresponds to an infinitesimally small feature according to our definition, so as the resolution goes to infinity the detected lengthscale will go to zero.

We should certainly make this clear in the README.

In principle we could emit a warning if there are sharp corners (as detected by OpenCV).

In principle we could also add an option for a square kernel (instead of a circular kernel), which breaks rotation invariance but might be useful in certain applications.

**Comment by ianwilliamson** [comment]
Okay, that makes sense and is reasonable. It would be interesting to expose something like a "kernel shape" option in the future. 

We should definitely expand the readme and also provide an illustration, if possible, of what should be expected.
